apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfylke-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/instance: fint-samtykke-frontend_trondelagfylke_no
  fintlabs.no/org-id: trondelagfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/trondelagfylke-no"
      - op: replace
        path: "/spec/env/0/value"
        value: "/trondelagfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/trondelagfylke-no"
      - op: replace
        path: "/spec/ingress/middlewares/0"
        value: "fint-samtykke-auth-forward-sso"
    target:
      kind: Application
      name: fint-samtykke-frontend


  - patch: |-
     - op: replace
       path: "/spec/basePath"
       value: "/trondelagfylke-no"
    target:
      kind: FLAISSso
      name: fint-samtykke-auth-forward-sso


