apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-samtykke-frontend
  namespace: rogfk-no
  labels:
    app.kubernetes.io/name: fint-samtykke-frontend
    app.kubernetes.io/component: samtykke-frontend


spec:
  port: 8000
  orgId: fylke.no
  image: ghcr.io/fintlabs/fint-samtykke-frontend
  imagePullPolicy: Always
  url:
    hostname: samtykke.vigoiks.no
    basePath: /beta/rogfk-no
  ingress:
    enabled: true
    middlewares:
      - fint-samtykke-auth-forward-sso
  env:
    - name: BASE_PATH
      value: path